Feat: updated models and api client
kysect/iwentys pull request #214
Opened 2021-07-28 12:18 UTC by Bibletoon

Close #201 and #202 
Гит немного сломался в процессе и продублировал коммит, вроде это не должно ничего сломать

2021-07-29 20:06 UTC, hrrrrustic reviewed
Хз ну я файлы с версткой сразу скипал, а так смотреть-то и нечего

2021-07-29 20:06 UTC, hrrrrustic commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/SubjectAssignments/MentorPages/SubjectAssignmentSubmitPage.razor.cs
> +            _hasReview = _submit is not null && _submit.State is SubmitState.Approved or SubmitState.Rejected;
```suggestion
            _hasReview = _submit is {State: is SubmitState.Approved or SubmitState.Rejected};
```

2021-07-29 20:06 UTC, hrrrrustic commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/SubjectAssignments/MentorPages/SubjectAssignmentSubmitPage.razor.cs
> +            _hasReview = _submit is not null && _submit.State is SubmitState.Approved or SubmitState.Rejected;
По памяти написал, проверь синтаксис в студии

2021-07-29 20:06 UTC, hrrrrustic commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/SubjectAssignments/MentorPages/SubjectAssignmentSubmitPage.razor.cs
> +            _confirmationModal?.Hide();
Хз выглядит странно, что в создании убирается какое-то подтверждение

2021-07-29 20:06 UTC, hrrrrustic commented on Source/Infrastructure/Iwentys.Infrastructure.DataAccess.Seeding/EntityGenerators/SubjectAssignmentGenerator.cs
> +                        if (RandomExtensions.Instance.Random.Int(0, 10) < 5)
Уже завезли тредсейфовый статичный рандом @FrediKats

2021-07-31 07:56 UTC, Bibletoon commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/SubjectAssignments/MentorPages/SubjectAssignmentSubmitPage.razor.cs
> +            _hasReview = _submit is not null && _submit.State is SubmitState.Approved or SubmitState.Rejected;
Райдер не смог понять, что от него хотят. Можно сурс на доку с применением этой штуки, так как впервые её вижу

2021-07-31 08:47 UTC, FrediKats requested changes

2021-07-31 08:47 UTC, FrediKats commented on Source/Domain/Iwentys.Domain/SubjectAssignments/SubjectAssignmentSubmit.cs
> +        public int ReviewerId { get; set; }
Может сразу и public IwentysUser Reviewer {}?

2021-07-31 08:47 UTC, FrediKats commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/SubjectAssignments/MentorPages/Components/DarkConfirmationModal.razor
> +            @*TODO: Find way how to sync colors with global theme*@
1. Добавь для этого компонента .scss файл, в него вынеси стили
2. В .scss можно сделать инклюд глобального scss, где прописаны цвета

2021-07-31 08:47 UTC, FrediKats commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/SubjectAssignments/MentorPages/Components/DarkConfirmationModal.razor
> +                    <button type="button" class="btn btn-secondary" data-dismiss="modal" @onclick="OnCancel">Close</button>
Хм. А они автоматически под цвет темы подгоняются? Почему не MudButton ?

2021-07-31 08:47 UTC, FrediKats commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/SubjectAssignments/MentorPages/SubjectAssignmentSubmitPage.razor
> +@using Iwentys.Endpoints.WebClient.Modules.SubjectAssignments.MentorPages.Components
Нужно завести ишую и подумать как воевать с этими ужасными юзингами :с

2021-07-31 10:22 UTC, FrediKats approved these changes

2021-07-31 11:10 UTC, hrrrrustic commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/SubjectAssignments/MentorPages/SubjectAssignmentSubmitPage.razor.cs
> +            _hasReview = _submit is not null && _submit.State is SubmitState.Approved or SubmitState.Rejected;
https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzmAPgAQEwEYCwAUJgMwAEApjAK5hkAqFKCRA3kWQPIwVkC8ZXHA70A7gHt+ZbEQC+RIqTI4yAQWDjgENhzJ6ljZmQBqEADbVerAOYUEAbnmEnSlQGEy7Qnv3lMAFjIAWQAKdU0IMk0AKwBKT10fHwA3CAAnMmApGLIoFE9TCwoQBiYEADpuXnEMwwqxcVl7RLInWSA

2021-07-31 11:11 UTC, hrrrrustic commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/SubjectAssignments/MentorPages/SubjectAssignmentSubmitPage.razor.cs
> +            _hasReview = _submit is not null && _submit.State is SubmitState.Approved or SubmitState.Rejected;
Доку хз, просто паттерн матчинг

2021-08-01 08:05 UTC, merged

2021-08-01 15:18 UTC, hrrrrustic commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/SubjectAssignments/MentorPages/SubjectAssignmentSubmitPage.razor
> +@using Iwentys.Endpoints.WebClient.Modules.SubjectAssignments.MentorPages.Components
Обновить до 6 дотнета и сделать файл с глоабльными юзингами?

2021-08-01 16:03 UTC, Bibletoon commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/SubjectAssignments/MentorPages/SubjectAssignmentSubmitPage.razor
> +@using Iwentys.Endpoints.WebClient.Modules.SubjectAssignments.MentorPages.Components
В блазоре и без 6 дотнета есть глобальные юзинги, но кмк такое себе компонент использующийся на одной странице глобально прописывать