feat: filter for mentor + colorful submits
kysect/iwentys pull request #217
Opened 2021-08-01 16:23 UTC by Kerenery

2021-08-01 16:26 UTC, Kerenery commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/SubjectAssignments/StudentPages/Components/SubjectAssignmentSubmitComponent.razor
> +                <MudPaper Class="p-4 h6" Style="@($"color:{Colors.Green.Accent3};")">
c 11 по 13 надо вырезать

2021-08-02 06:56 UTC, Bibletoon requested changes

2021-08-02 06:56 UTC, Bibletoon commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/SubjectAssignments/StudentPages/Components/SubjectAssignmentSubmitComponent.razor
> +                        <MudPaper Class="p-4 h6" Style="@($"color:{Colors.Green.Accent3};")">
Прописывать стиль прямо в элементе как-то не очень кмк, да и выглядит страшно, может лучше поместить внутрь MudText и у него уже прописать Color?
Типо такого:
```html
<MudPaper Class="p-4">
    <MudText Color="Color.Success" Typo="Typo.h6">
        Approved (@Submit.ApproveTimeUtc)
    </MudText>
</MudPaper>
```

2021-08-02 06:56 UTC, Bibletoon commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/SubjectAssignments/MentorPages/SubjectAssignmentSubmitJounalPage.razor
> +    private string searchString = "";
Как-то странно что часть кода у нас в CodeBehind, а часть на странице

2021-08-02 06:56 UTC, Bibletoon commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/SubjectAssignments/MentorPages/SubjectAssignmentSubmitJounalPage.razor
> +    private bool FilterFunc(SubjectAssignmentSubmitDto student)
Может как-то в названии функции указать, что она используется в поиске, например назвать `SearchFilterFunc` (лучше подумать и подобрать чуть более лаконичное название, чем моё предложение)
Ну это немного вкусовщина, просто я посмотрев на сигнатуру метода не до конца понял что он делает

2021-08-02 10:11 UTC, Bibletoon approved these changes
Inspector мне нравится ещё меньше, но ладно

2021-08-02 10:17 UTC, Kerenery commented
> Inspector мне нравится ещё меньше, но ладно

Просто когда я вижу inspector, представляю лупу, но готов поменять.

2021-08-02 10:26 UTC, Bibletoon commented
> > Inspector мне нравится ещё меньше, но ладно
> 
> Просто когда я вижу inspector, представляю лупу, но готов поменять.
> 

Вообще называть методы существительными плохо, так как метод - это действие. Ну и моя первая ассоциация это инспектор гаджет, ну или иконка из средств разработчика в браузере

2021-08-03 07:17 UTC, FrediKats requested changes

2021-08-03 07:17 UTC, FrediKats commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/SubjectAssignments/MentorPages/SubjectAssignmentSubmitJounalPage.razor
> +                        <MudTh><MudTableSortLabel SortBy="new Func<SubjectAssignmentSubmitDto, object>(x => x.SubjectAssignmentTitle)">Assignment</MudTableSortLabel></MudTh>
А оно не работает, если просто лямбду написать без new Func?

2021-08-03 07:17 UTC, FrediKats commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/SubjectAssignments/MentorPages/SubjectAssignmentSubmitJounalPage.razor.cs
> +            if (student.Student.SecondName.Contains(_searchString, StringComparison.OrdinalIgnoreCase))
Ой, чувствую когда-то станет больно, если я захочу по названию ассаймента найти, а у кого-то такой юзернейм будет. Ну да ладно.

2021-08-03 16:20 UTC, Kerenery commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/SubjectAssignments/MentorPages/SubjectAssignmentSubmitJounalPage.razor
> +                        <MudTh><MudTableSortLabel SortBy="new Func<SubjectAssignmentSubmitDto, object>(x => x.SubjectAssignmentTitle)">Assignment</MudTableSortLabel></MudTh>
no, там требуется спецификация.
я здесь смотрел https://github.com/Garderoben/MudBlazor/blob/master/src/MudBlazor.Docs/Pages/Components/Table/Examples/TableInlineEditExample.razor
ничего больше не нашел.

2021-08-11 08:10 UTC, FrediKats approved these changes

2021-08-11 08:10 UTC, FrediKats commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/SubjectAssignments/MentorPages/SubjectAssignmentSubmitJournalPage.razor
> +@using System.Net.Mail
А это зачем?

2021-08-11 09:51 UTC, Kerenery commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/SubjectAssignments/MentorPages/SubjectAssignmentSubmitJournalPage.razor
> +@using System.Net.Mail
сори за райдер

2021-08-11 10:14 UTC, merged