Feat: subjects & assignments collapse
kysect/iwentys pull request #227
Opened 2021-08-11 01:03 UTC by Mihinator3000

Добавил возможность сворачивать/разворачивать сабджекты и ассайнменты. Код конечно выглядит совсем не очень, но я не знаю как это еще можно сделать. Нужно еще будет подумать, как показать юзеру, что ассайнменты могут быть развернуты, пока из идей только сделать значки, как с сабджектами

2021-08-11 06:25 UTC, Bibletoon requested changes
Выглядит как изобретение велосипеда, в MudBlazor есть [Expansion Panels](https://mudblazor.com/components/expansionpanels), как мне кажется их функционала вполне достаточно для того, что нам надо

2021-08-11 22:23 UTC, Mihinator3000 commented
> Выглядит как изобретение велосипеда, в MudBlazor есть [Expansion Panels](https://mudblazor.com/components/expansionpanels), как мне кажется их функционала вполне достаточно для того, что нам надо

Для сворачивания сабджектов работает идеально, не спорю. Но с ассайнментами опять возникает проблема, что у менторов я не могу свернуть кнопки edit/delete/recover вместе с остальным контентом, тут либо разбивать SubjectAssignmentComponent на менторов и студентов, либо опять делать бинды. А второе скорее всего будет выглядеть косячно, учитывая, что у Expansion Panels есть свои анимации. Есть идеи какие-нибудь?

2021-08-12 12:48 UTC, Bibletoon commented
Можно действительно сделать отдельные компоненты для менторов и студентов, представляющие собой MudExpansionPanel, которые где-то внутри у себя будут вызывать SubjectAssignmentComponent (В теории из SubjectAssignmentComponent можно удалить заголовок, так как он будет в панели, но лучше оставить и просто в панели писать его маленьким)

2021-08-14 07:47 UTC, Bibletoon approved these changes
Единственное замечание: лучше в названиях слово `Component` написать в конце.
`SubjectAssignmentComponentHeader` подчёркивает, что это заголовок для `SubjectAssignmentComponent`, но мы можем использовать его в любом месте, где хотим поставить заголовок для `SubjectAssignment`, так что название `SubjectAssignmentHeaderComponent` подходит больше, так как просто обозначает что это за компонент, без привязки к `SubjectAssignmentComponent`

2021-08-14 10:37 UTC, Mihinator3000 commented
@Bibletoon, я поправил нейминги, мерджить прав нет

2021-08-14 11:48 UTC, merged