Feat: add button
kysect/iwentys pull request #231
Opened 2021-08-18 09:34 UTC by luck-o-o-luck

2021-08-18 09:45 UTC, Bibletoon requested changes
Немного сложно разобраться что вообще произошло: название (add button) вообще ни о чём конкретном не говорит.
Так же если этот pr закрывает какую-то ишую, то её стоит прикрепить (в описании написать Close #номер-задачи)

2021-08-18 09:45 UTC, Bibletoon commented on Source/Endpoints/Iwentys.Endpoints.Sdk/ApiClients/IwentysApiClient.cs
> +        public bool IsStudentAssignment { get; set; }
Смею предположить, что это поле было добавлено руками. Api client у нас генерируется по swaggerу с помощью nswag studio, если добавилось новое поле, то стоит перегенерировать клиент.
Где-то в доке есть гайд, но он вроде не актуальный, можно разобраться и как раз переписать!

2021-08-18 09:45 UTC, Bibletoon commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/SubjectAssignments/MentorPages/Components/MentorSubjectAssignmentComponent.razor
> +                        assignment.IsStudentAssignment = false;
Если я правильно понял и это поле используется только для того, что бы внутри компонента понимать, откуда был вызван компонент - со стороны студента или ментора, то лучше просто добавить параметр в сам компонент, а не делать костыли

2021-08-22 08:17 UTC, FrediKats reviewed
В целом выглядит ок, но не исправилось то, о чём писал выше @Bibletoon.
- Имя пр
- Не прилинкованна ишуя к которой PR относится.

2021-08-22 08:17 UTC, FrediKats commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/SubjectAssignments/StudentPages/StudentSubjectAssignmentPage.razor
> +@page "/subject/{SubjectId:int}/assignments"
А тут diff из-за \r в конце?)

2021-08-22 08:37 UTC, luck-o-o-luck commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/SubjectAssignments/StudentPages/StudentSubjectAssignmentPage.razor
> +@page "/subject/{SubjectId:int}/assignments"
Забавный факт - я вообще не трогаю эти строчки, а в итоге появляется. В тот раз, когда изменения во всех файлах якобы были, в своих я руками отменяла. А в этот раз я поверхностно глянула в кракене.

2021-08-22 08:38 UTC, FrediKats approved these changes

2021-08-22 09:43 UTC, merged