Feat: add account managment
kysect/iwentys pull request #244
Opened 2021-08-29 07:05 UTC by Bibletoon

Знаю что плохо так делать, но:
Closes #218
Closes #219 
Closes #220 
Closes #221 

Ui выступает в качестве некого MVP, пользоваться можно, но для комфорта хотелось бы несколько изменений, возможно поменять вёрстку на странице со списком менторов (на это всё заведу ишуи)

2021-08-29 07:09 UTC, Bibletoon commented
Понятия не имею почему +15к строк, гит сломался

2021-08-29 14:20 UTC, FrediKats requested changes

2021-08-29 14:20 UTC, FrediKats commented on Source/Domain/Iwentys.Domain/Study/GroupSubject.cs
> +            if (PracticeMentors.All(pm => pm.UserId != practiceMentor.Id))
else thr?

2021-08-29 14:20 UTC, FrediKats commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/AccountManagement/MentorsManagement/MentorsJournalPage.razor
> +                                                <MudText><MudChip Tag="new MentorIdentifier() { GroupSubjectId = groupMentors.Id, MentorId = practiceMentor.Id }" Color="Color.Secondary" OnClose="Remo
Очень странно читать `GroupSubjectId = groupMentors.Id`
Складывается ощущение, что слева и справа - id разных сущностей.

2021-08-29 14:20 UTC, FrediKats commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/AccountManagement/MentorsManagement/MentorsJournalPage.razor.cs
> +                    g => g.PracticeMentors.Any(m => m.Id == userToDelete.MentorId));
Хочется вынести эту сложную логику в метод. Чтобы он отвечал за поиск сущности по id

2021-08-29 14:20 UTC, FrediKats commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/AccountManagement/MentorsManagement/MentorsJournalPage.razor.cs
> +                var mentor = group.PracticeMentors.FirstOrDefault(m => m.Id == userToDelete.MentorId);
В теории же можно в MentorIdentifier хранить сразу Mentor, а не только его id

2021-08-29 14:20 UTC, FrediKats commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/AccountManagement/MentorsManagement/AddMentorPage.razor.cs
> +        [Inject] public ISnackbar Snackbar { get; set; }
А почему там выше атрибут на отдельной строке, а тут на одной?

2021-08-29 14:20 UTC, FrediKats commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/AccountManagement/MentorsManagement/AddMentorPage.razor.cs
> +            if (_groups.Any(g => g.Name == _groupName.Substring(0,5)))
А почему там SubString?

2021-08-29 23:36 UTC, hrrrrustic commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/AccountManagement/MentorsManagement/AddMentorPage.razor.cs
> +            if (_groups.Any(g => g.Name == _groupName.Substring(0,5)))
Реально, надо же слайсить спан!

2021-08-30 08:27 UTC, Bibletoon commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/AccountManagement/MentorsManagement/AddMentorPage.razor.cs
> +            if (_groups.Any(g => g.Name == _groupName.Substring(0,5)))
Потому что такая штука на беке, надо будет завести ишую на переработку механизма создания имени группы, текущий как минимум умрёт на специализациях

2021-08-30 08:29 UTC, Bibletoon commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/AccountManagement/MentorsManagement/MentorsJournalPage.razor.cs
> +                                         || g.PracticeMentors.Any(m => m.Id == _currentUser.Id))).ToList();
Ну хз, Вызывать 2 метода, типа получить всех и получить только предметы текущего препода?

2021-08-30 08:30 UTC, Bibletoon commented on Source/Domain/Iwentys.Domain/Study/GroupSubject.cs
> +            return LectorMentorId == user.Id || PracticeMentors.Any(pm=>pm.UserId == user.Id);
Кекв, что могу сказать

2021-08-30 08:32 UTC, Bibletoon commented on Source/Domain/Iwentys.Domain/Study/GroupSubject.cs
> +        public virtual List<GroupSubjectMentor> PracticeMentors { get; init; }
Просто сделать одно поле Mentors в котором и практики, и лектор? Ну тогда, скорее всего, могут появиться проверки типа "лектор только один на группу", хотя можно просто забить и поддержать возможность 2+ лекторов на группу.

2021-08-30 08:33 UTC, Bibletoon commented on Source/Modules/Iwentys.Modules.AccountManagement/Mentors/Commands/AddMentor.cs
> +                    var groupSubject = await _dbContext.GroupSubjects.FirstOrDefaultAsync(
Валидно

2021-08-30 08:35 UTC, Bibletoon commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/AccountManagement/MentorsManagement/MentorsJournalPage.razor.cs
> +            catch (ApiException e)
Ну хз, а если ошибка будет не в запросе, а в методах MudBlazor? Группа добавится (или что конкретно в этом кетче делается), но выведется сообщение о том, что не добавилась

2021-08-30 08:37 UTC, Bibletoon commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/AccountManagement/MentorsManagement/MentorsJournalPage.razor.cs
> +                    g => g.PracticeMentors.Any(m => m.Id == userToDelete.MentorId));
Впринципе можно extension придумать

2021-08-31 15:39 UTC, hrrrrustic reviewed
Бтв не понял почему везде `set` вместо `init`

2021-08-31 15:39 UTC, hrrrrustic commented on Source/Domain/Iwentys.Domain/AccountManagement/Mentors/Dto/GroupMentorsDto.cs
> +        public GroupMentorsDto(int id, string name, IReadOnlyList<MentorDto> lectorMentors, IReadOnlyList<MentorDto> Mentors)
Чет не понял что тут вообще происходит с последним аргументом

2021-08-31 15:39 UTC, hrrrrustic commented on Source/Domain/Iwentys.Domain/AccountManagement/Mentors/Dto/GroupMentorsDto.cs
> +        public GroupMentorsDto()
Это что-то для десериализации?

2021-08-31 15:39 UTC, hrrrrustic commented on Source/Domain/Iwentys.Domain/AccountManagement/Mentors/Dto/SubjectMentorCreateArgs.cs
> +        public List<int> GroupSubjectIds { get; set; }
ридонли?

2021-08-31 15:39 UTC, hrrrrustic commented on Source/Domain/Iwentys.Domain/Study/GroupSubject.cs
> +            {
хайповое форматирование

2021-08-31 15:39 UTC, hrrrrustic commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/AccountManagement/MentorsManagement/MentorsJournalPage.razor.cs
> +                g => g.Mentors.Contains(userToDelete.Mentor));
Выглядит страшно если чесн
Я как-то за 5 раз даже распарсить не смог...

2021-08-31 15:39 UTC, hrrrrustic commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/AccountManagement/MentorsManagement/MentorsJournalPage.razor.cs
> +                    g => g.Mentors.Any(m=>m.Id == _currentUser.Id))).ToList();
+ 1 к комменту выше
Такое ощущение, что вместо списка тут просто словарь какой-то нужен

2021-08-31 15:39 UTC, hrrrrustic commented on Source/Modules/Iwentys.Modules.AccountManagement/Mentors/Commands/AddMentor.cs
> +                    gs=>gs.SubjectId==request.Args.SubjectId && request.Args.GroupSubjectIds.Contains(gs.StudyGroupId))
че по пробелам

2021-08-31 15:39 UTC, hrrrrustic commented on Source/Modules/Iwentys.Modules.AccountManagement/Mentors/Commands/AddMentor.cs
> +            public async Task<Unit> Handle(Command request, CancellationToken cancellationToken)
А в чем суть юнита здесь?

2021-08-31 19:10 UTC, hrrrrustic commented on Source/Modules/Iwentys.Modules.AccountManagement/Mentors/Commands/AddMentor.cs
> +            public async Task<Unit> Handle(Command request, CancellationToken cancellationToken)
Кринж

2021-09-01 17:08 UTC, Bibletoon commented on Source/Domain/Iwentys.Domain/AccountManagement/Mentors/Dto/GroupMentorsDto.cs
> +        public GroupMentorsDto()
Для автомаппера (как и set)
Можно, конечно, сделать маппинг по параметрам конструктора, но meh

2021-09-11 07:33 UTC, FrediKats requested changes

2021-09-11 07:33 UTC, FrediKats commented on Source/Domain/Iwentys.Domain/AccountManagement/Mentors/Dto/GroupMentorsDto.cs
> +        public GroupMentorsDto(int id, string name, IReadOnlyList<MentorDto> mentors)
Есть кста отличный план - вызывать пустой конструктор из не пустого, чтобы он не отображался как unused.

2021-09-11 07:33 UTC, FrediKats commented on Source/Domain/Iwentys.Domain/Study/GroupSubject.cs
> +        public GroupSubject(Subject subject, StudyGroup studyGroup, StudySemester studySemester, IwentysUser lectorMentor)
Может лектора тоже убрать из конструктора и добавлять методом?

2021-09-11 07:33 UTC, FrediKats commented on Source/Domain/Iwentys.Domain/Study/GroupSubject.cs
> +            if (Mentors.All(pm => !pm.IsLector || pm.UserId != practiceMentor.Id))
Вынеси эту проверку как метод, явно ещё понадобиться и будет более читаемо.

2021-09-11 07:33 UTC, FrediKats commented on Source/Domain/Iwentys.Domain/Study/GroupSubject.cs
> +            } else {
1) Форматирование
2) do-8

2021-09-11 07:33 UTC, FrediKats commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/AccountManagement/MentorsManagement/AddMentorPage.razor.cs
> +            catch (ApiException e)
Гитхаб предлагает убрать unused e.

2021-09-11 07:33 UTC, FrediKats commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/AccountManagement/MentorsManagement/MentorsJournalPage.razor.cs
> +                }
Форматирование

2021-09-11 07:33 UTC, FrediKats commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/AccountManagement/MentorsManagement/MentorsJournalPage.razor.cs
> +                var group = GetGroupByMentor(userToDelete);
>ByMentor
>userToDelete

Лучше всё же пытаться в едином стиле неймить, я думаю.

2021-09-11 07:33 UTC, FrediKats commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/AccountManagement/MentorsManagement/MentorsJournalPage.razor.cs
> +            catch (ApiException e)
Не оч правильно выразился
`catch (ApiException)`

2021-09-11 07:33 UTC, FrediKats commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/AccountManagement/MentorsManagement/MentorsJournalPage.razor.cs
> +            var subject = _allSubjectsMentors.First(
А оно не сломается если будет >1 сабджекта под данным ментором?

2021-09-11 07:33 UTC, FrediKats commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/AccountManagement/MentorsManagement/MentorsJournalPage.razor.cs
> +                sm => sm.Groups.Any(g => g.Mentors.Contains(userToDelete.Mentor)));
В теории, хотелось бы просто в классах инкапсулировать логику эту, добавить им метод `HasMentor` или что-то такое. Но это модели, которые генерятся... Разве что экстеншен методами повыносить 🤔

2021-09-12 12:30 UTC, Bibletoon commented on Source/Endpoints/Iwentys.Endpoints.WebClient/Modules/AccountManagement/MentorsManagement/MentorsJournalPage.razor.cs
> +            var subject = _allSubjectsMentors.First(
Ну у нас в замоканых данных у всех предметов один и тот же ментор и всё работает.

2021-09-12 13:58 UTC, FrediKats approved these changes

2021-09-12 13:58 UTC, merged